### ISSUE TITLE
Event didn't get called

### ISSUE THREAD

**Issue by chenliyang1024** [pdfplum/pdfplum#27]
### Description

![image](https://github.com/pdfplum/pdfplum/assets/16925951/6fad9566-97f7-4f08-9201-bc4453dc4ef4)
![image](https://github.com/pdfplum/pdfplum/assets/16925951/4acff70f-a17e-4618-ad79-8807cc8625f2)
![image](https://github.com/pdfplum/pdfplum/assets/16925951/46ea392d-7132-45d4-8dbc-e7298556b478)

I've enabled the event, but it never get called

### Steps to reproduce the behavior

![image](https://github.com/pdfplum/pdfplum/assets/16925951/6fad9566-97f7-4f08-9201-bc4453dc4ef4)
![image](https://github.com/pdfplum/pdfplum/assets/16925951/4acff70f-a17e-4618-ad79-8807cc8625f2)
![image](https://github.com/pdfplum/pdfplum/assets/16925951/46ea392d-7132-45d4-8dbc-e7298556b478)

### Logs

![image](https://github.com/pdfplum/pdfplum/assets/16925951/2ad1dd16-6fdc-4da2-9e7f-668284690711)

**Comment by sassanh** [comment]
Sorry for the late response, I was in vacation.

It should be fixed in 0.17.2, you can check it by installing the release candidates using these links:

- https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.17.1-rc.2
- https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/http-pdf-generator@0.17.1-rc.2

**Comment by chenliyang1024** [comment]
@sassanh I tried with the new release, the event still not triggered. I've tried to print the event, but no lucks.
![image](https://github.com/pdfplum/pdfplum/assets/16925951/c09b9b41-8d50-41c2-ad16-6255023f63b5)
This is how I did, can you confirm this is correct?

**Comment by sassanh** [comment]
For reference, this breaking change is done so that pdfplum event names are aligned with the conventions mentioned in [this piece of documentation](https://firebase.google.com/docs/extensions/publishers/user-hooks#eventarc) about naming the events:

> The type identifier is made of several dot-delimited fields. The [publisher ID](https://firebase.google.com/docs/extensions/publishers/register), extension name, and event name fields are required. The version field is recommended. Choose a unique and descriptive event name for each event type you publish.

**Comment by sassanh** [comment]
Sample working code for a function triggered by the event:

```typescript
import {onCustomEventPublished} from "firebase-functions/v2/eventarc";
import * as logger from "firebase-functions/logger";

export const eventhandler = onCustomEventPublished(
  "pdfplum.http-pdf-generator.v1.complete",
  (event) => {
    logger.info("PDF created successfully", event);
  });
```

**Comment by chenliyang1024** [comment]
Hi @sassanh, 

I'm not sure why i still can't see the event being triggered. 
![image](https://github.com/pdfplum/pdfplum/assets/16925951/75a6751f-20d1-4d47-a58c-bd4e9acee19c)

Did I miss anything here?

**Comment by sassanh** [comment]
Are you checking the logs in https://console.cloud.google.com/logs? What is your log query? Try emptying the query (checking logs with no filters). When you open the logs from the extension page, it opens the log viewer with a filter that only shows extension's logs and not the logs of your custom function.

It would be nice if you copy the actual text instead of screenshots ;)

**Comment by chenliyang1024** [comment]
> Are you checking the logs in https://console.cloud.google.com/logs? What is your log query? Try emptying the query (checking logs with no filters). When you open the logs from the extension page, it opens the log viewer with a filter that only shows extension's logs and not the logs of your custom function.
> 
> It would be nice if you copy the actual text instead of screenshots ;)

![image](https://github.com/pdfplum/pdfplum/assets/16925951/881fb10d-c96d-4e6c-b347-b895ceaa9b33)

The PDF is generated, but the complete event is not triggered.

**Comment by chenliyang1024** [comment]
> What is your log query? I mean the text in this box: <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/1270688/313752040-85c67a01-332d-4bd4-bacc-2e01da50bc4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzgyMzIsIm5iZiI6MTcxMDc3NzkzMiwicGF0aCI6Ii8xMjcwNjg4LzMxMzc1MjA0MC04NWM2N2EwMS0zMzJkLTRiZDQtYmFjYy0yZTAxZGE1MGJjNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTYwNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI5MTgyYmMxODIyNmE3ZDg0MWNiZTVmNmY1NGFhNDAxNTY1ZDdiMTgzMmE3OTczZWM3ZTZlMTBiNmZkNGM4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eapjSYP4DYd0Gz81WP50yw5edQ6I_E5Y_2y6DoywAEs">

empty

**Comment by sassanh** [comment]
@chenliyang1024 Did it eventually work for you?

**Comment by chenliyang1024** [comment]
> @chenliyang1024 Did it eventually work for you?

No, the event handler function still not being called. 
<img width="799" alt="image" src="https://github.com/pdfplum/pdfplum/assets/16925951/a92845d2-1b4e-4dd9-866f-24ebd309f063">
This function is successfully deployed to the firebase function, but it's never called.

beside the code, do I need to do anything else?

**Comment by sassanh** [comment]
I'm sorry if it is still an issue for you, but I just tested this throughly as part of testing [another issue](https://github.com/pdfplum/pdfplum/issues/38) and I saw all events are dispatched as expected and the functions are being triggered.
Unfortunately I can't do anything more without a reproduction steps that reproduces the issue on my side too.
